package SuiteRunner;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import ProfileManagement.ChangePassword.ValidateCurrentPasswordWhenChangingPassword;
import ProfileManagement.ChangePassword.VerifyPasswordChangeWorks;
import ProfileManagement.ChangePaymentInfo.VefiryChangePaymentInfoDetailsUpdatedSuccessfully;
import ProfileManagement.ChangePin.VerifyChangePinCodeDetailsUpdatedSuccessfully;
import ProfileManagement.EditProfile.EditXidioAddressInProfileManagement;
import ProfileManagement.EditProfile.EditXidioCityInProfileManagement;
import ProfileManagement.EditProfile.EditXidioLastNameInProfileManagement;
import ProfileManagement.EditProfile.EditXidioStateInProfileManagement;
import ProfileManagement.EditProfile.EditXidioUserNameInProfileManagement;
import ProfileManagement.EditProfile.EditXidioZipInProfileManagement;
import ProfileManagement.EditProfile.ValidateUNameFieldByDeletingValueInPaymentManagement;
import UserAuthentication.ResettingPassword.ResetTheXidioPassword;
import UserAuthentication.ResettingPassword.ResetTheXidioPasswordWithWrongEmail;
import UserAuthentication.ResettingPassword.ResetXidioPasswordWithoutProvidingEmailID;
import UserAuthentication.UserLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingInValidPassword;
import UserAuthentication.UserLogin.ValidateUserLoginUsingInValidCredentials.LoginToXidioApplicationUsingInValidUserName;
import UserAuthentication.UserLogin.ValidateUserLoginUsingValidCredentials.LoginToXidioApplicationWithValidCredentials;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationByClickingActivation;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationByEnteringInValidEmail;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationByEnteringInValidLengthOfPassword;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationByEnteringInValidMobileNumber;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationByEnteringInValidZip;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationByEnteringInValidZipLength;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationByEnteringNonCapitalLetterPassword;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationByEnteringNonDigitPassword;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationBySkipingPaymentStepAndActivationStep;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationDirectlyWithPaymentDetailsWithoutPersonalInfo;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationUsingValidCredentials;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithValidCredentialByDeclineTermAndCondition;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithoutEnteringAddress;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithoutEnteringCity;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithoutEnteringEmail;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithoutEnteringFirstName;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithoutEnteringLastName;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithoutEnteringMobileNumber;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithoutEnteringPassword;
import UserAuthentication.UserRegistration.RegisterToXidioApplicationWithoutEnteringZip;
import VideoManagement.VideoSearchFunctionality.FeedBack.VerifyFeedbackSubmitedSuccessfully;
import VideoManagement.VideoSearchFunctionality.SearchVideoByCategory.EnsureSearchChannelStoreIsWorkingFine;
import VideoManagement.VideoSearchFunctionality.SearchVideoByCategory.VerifySelectedCategoryAndSubCategoryVideosAreDisplayed;
import VideoManagement.VideoSearchFunctionality.SearchVideoByCategory.VerifySubcriptionOfPaidVideo;

@RunWith(Suite.class)
@Suite.SuiteClasses({
	//Start Registration Module....
	RegisterToXidioApplicationByClickingActivation.class,
	RegisterToXidioApplicationByEnteringInValidEmail.class,
	RegisterToXidioApplicationByEnteringInValidLengthOfPassword.class,
	RegisterToXidioApplicationByEnteringInValidMobileNumber.class,
	RegisterToXidioApplicationByEnteringInValidZip.class,
	RegisterToXidioApplicationByEnteringInValidZipLength.class,
	RegisterToXidioApplicationByEnteringNonCapitalLetterPassword.class,
	RegisterToXidioApplicationByEnteringNonDigitPassword.class,
	RegisterToXidioApplicationBySkipingPaymentStepAndActivationStep.class,
	RegisterToXidioApplicationDirectlyWithPaymentDetailsWithoutPersonalInfo.class,
	RegisterToXidioApplicationUsingValidCredentials.class,
	RegisterToXidioApplicationWithoutEnteringAddress.class,
	RegisterToXidioApplicationWithoutEnteringCity.class,
	RegisterToXidioApplicationWithoutEnteringEmail.class,
	RegisterToXidioApplicationWithoutEnteringFirstName.class,
	RegisterToXidioApplicationWithoutEnteringLastName.class,
	RegisterToXidioApplicationWithoutEnteringMobileNumber.class,
	RegisterToXidioApplicationWithoutEnteringPassword.class,
	RegisterToXidioApplicationWithoutEnteringZip.class,
	RegisterToXidioApplicationWithValidCredentialByDeclineTermAndCondition.class,
	//End Start Registration Module....
	
	//Start Profile Module....
	ValidateCurrentPasswordWhenChangingPassword.class,
	VerifyPasswordChangeWorks.class,
	VefiryChangePaymentInfoDetailsUpdatedSuccessfully.class,
	VerifyChangePinCodeDetailsUpdatedSuccessfully.class,
	EditXidioAddressInProfileManagement.class,
	EditXidioCityInProfileManagement.class,
	EditXidioLastNameInProfileManagement.class,
	EditXidioStateInProfileManagement.class,
	EditXidioUserNameInProfileManagement.class,
	EditXidioZipInProfileManagement.class,
	ValidateUNameFieldByDeletingValueInPaymentManagement.class,
	//End Profile Module....
	
	//Start Profile Module....
	ResetTheXidioPassword.class,
	ResetTheXidioPasswordWithWrongEmail.class,
	ResetXidioPasswordWithoutProvidingEmailID.class,
	LoginToXidioApplicationUsingInValidPassword.class,
	LoginToXidioApplicationUsingInValidUserName.class,
	LoginToXidioApplicationWithValidCredentials.class,
	
	//Start Video Management Module....
	VerifyFeedbackSubmitedSuccessfully.class,
	EnsureSearchChannelStoreIsWorkingFine.class,
	VerifySelectedCategoryAndSubCategoryVideosAreDisplayed.class,
	VerifySubcriptionOfPaidVideo.class
	//Start Video Management Module....
})
public class runTestSuite {

}

